stages:
  - build
  - deploy

variables:
  BACKEND_IMAGE: $CI_REGISTRY_IMAGE/backend
  FRONTEND_IMAGE: $CI_REGISTRY_IMAGE/frontend
  REDIS_IMAGE: $CI_REGISTRY_IMAGE/redis
  COMPOSE_PATH: /data/docker-compose/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME

mirror-redis:
  stage: build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker pull redis:7-alpine
    - docker tag redis:7-alpine $REDIS_IMAGE:7-alpine
    - docker push $REDIS_IMAGE:7-alpine

build-backend:
  stage: build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - >
      docker build --cache-from $BACKEND_IMAGE:$CI_COMMIT_REF_SLUG
      -t $BACKEND_IMAGE:$CI_COMMIT_REF_SLUG
      -f ./backend/Dockerfile ./backend
    - docker push $BACKEND_IMAGE:$CI_COMMIT_REF_SLUG

build-frontend:
  stage: build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - >
      docker build --cache-from $FRONTEND_IMAGE:$CI_COMMIT_REF_SLUG
      -t $FRONTEND_IMAGE:$CI_COMMIT_REF_SLUG
      -f ./frontend/Dockerfile .
    - docker push $FRONTEND_IMAGE:$CI_COMMIT_REF_SLUG

deploy:
  stage: deploy
  image: governmentpaas/git-ssh
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  before_script:
    - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )"
    - "which envsubst || apk add --no-cache gettext"
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $SSH_SERVER_HOST >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh -T finuser@$SSH_SERVER_HOST docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - ssh finuser@$SSH_SERVER_HOST mkdir -p $COMPOSE_PATH
    - envsubst < docker-compose.prod.yml > /tmp/docker-compose.rendered.yml
    - scp /tmp/docker-compose.rendered.yml finuser@$SSH_SERVER_HOST:$COMPOSE_PATH/docker-compose.yml
    - |
      ssh finuser@$SSH_SERVER_HOST "
        cd $COMPOSE_PATH &&
        docker-compose pull &&
        docker-compose stop celery-beat &&
        docker-compose rm -f celery-beat &&
        docker volume rm ${CI_PROJECT_NAME}_celery_beat_schedule || true &&
        docker-compose up -d --remove-orphans
      "
