x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "20m"
    max-file: "5"

services:
  redis:
    image: ${REDIS_IMAGE}:7-alpine
    restart: always
    logging: *default-logging

  backend:
    image: ${BACKEND_IMAGE}:${CI_COMMIT_REF_SLUG}
    restart: always
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - PIP_INDEX_URL=https://pypi.org/simple/
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - python_envs:/data/pyenvs
    command: >
      sh -c "printf 'precedence ::ffff:0:0/96  100\n' >> /etc/gai.conf &&
             alembic upgrade head &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000"
    logging: *default-logging

  celery-worker:
    image: ${BACKEND_IMAGE}:${CI_COMMIT_REF_SLUG}
    restart: always
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - PIP_INDEX_URL=https://pypi.org/simple/
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - python_envs:/data/pyenvs
    command: >
      sh -c "printf 'precedence ::ffff:0:0/96  100\n' >> /etc/gai.conf &&
             celery -A app.celery_app worker --queues=high,normal,default --concurrency=2 --loglevel=info"
    logging: *default-logging

  celery-beat:
    image: ${BACKEND_IMAGE}:${CI_COMMIT_REF_SLUG}
    restart: always
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
    command: celery -A app.celery_app beat --scheduler app.beat_schedule.DatabaseScheduler --loglevel=info --schedule /data/celerybeat-schedule
    volumes:
      - celery_beat_schedule:/data
    logging: *default-logging

  frontend:
    image: ${FRONTEND_IMAGE}:${CI_COMMIT_REF_SLUG}
    restart: always
    depends_on:
      - backend
    ports:
      - "8090:80"
    logging: *default-logging

volumes:
  celery_beat_schedule:
  python_envs:

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: "1400"
